
version: '3'
services:
  your-app:
    image: category
    ports:
      - "2025:2025"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/china_ayur
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
